server:
  port: 8767

spring:
  application:
    name: gateway-zuul   #指定服务名

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:   #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: http://localhost:8761/eureka/    # 指定 Eureka Server 地址

zuul:
  routes:
    eureka-client:
      path: /client/**
      serviceId: eureka-client

